courier/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("product/", include("product.urls", namespace="product")),
    path("user/", include("useraccount.urls", namespace="user")),
]

product/urls.py
from django.urls import path
from product.views import create_product, list_product, edit_product, delete_product, CreateProduct, logout_view

app_name = "product"

urlpatterns = [
    path("add-product/", CreateProduct.as_view(), name="add_product"),
    path("list-product/", list_product, name="list_product"),
    path("edit-product/<int:product_id>/", edit_product, name="edit_product"),
    path("delete-product/<int:product_id>/", delete_product, name="delete_product"),
    path("logout/", logout_view, name="logout"),
]

useraccount/urls.py
from django.urls import path
from useraccount.views import UserLogin, UserSignupView, send_email_to_user

app_name = "user"

urlpatterns = [
    path("login/", UserLogin.as_view(), name="login"),
    path("register/", UserSignupView.as_view(), name="register"),
    path("send-mail/", send_email_to_user, name="send-mail"),
]

product/models.py
from django.db import models
from django.contrib.auth.models import User


class Weight(models.Model):
    weight_range = models.CharField(max_length=255, unique=True)
    price = models.CharField(max_length=255)

    def __str__(self):
        return self.weight_range

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

class Product(models.Model):
    STATUS_CHOICES = (
        ("pending", "PENDING"),
        ("delivered", "DELIVERED"),
        ("returned", "RETURNED")
    )
    name = models.CharField(max_length=255)
    price = models.CharField(max_length=255)
    customer_fullname = models.CharField(max_length=255)
    customer_contact1 = models.CharField(max_length=255)
    customer_contact2 = models.CharField(max_length=255, null=True, blank=True)
    customer_address = models.CharField(max_length=255)
    status = models.CharField(max_length=50, choices=STATUS_CHOICES)
    remarks = models.TextField(null=True, blank=True)
    weight = models.ForeignKey(Weight, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if self.pk is None:
            self.status = "pending"
        super().save(*args, **kwargs)

useraccount/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avtar = models.ImageField(upload_to="avtar/", null=True, blank=True)
    contact = models.CharField(max_length=255, null=True, blank=True)
    address = models.CharField(max_length=255, null=True, blank=True)
    bank_name = models.CharField(max_length=255, null=True, blank=True)
    bank_branch = models.CharField(max_length=255, null=True, blank=True)
    bank_account = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return str(self.user)

@receiver(post_save, sender=User)
def update_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

product/forms.py
from django import forms
from product.models import Product

# class ProductCreateForm(forms.Form):
#     name = forms.CharField()
#     price = forms.CharField()
#     customer_name = forms.CharField()

class ProductCreateForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "__all__"
        exclude = ("status", "remarks", "user", )

useraccount/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"
        self.fields["password1"].help_text = "Your password must contain at least 8 characters."

product/views.py
from django.shortcuts import render, reverse, get_object_or_404
from product.forms import ProductCreateForm
from product.models import Product
from django.http import HttpResponseRedirect, HttpResponse
from django.views.generic import CreateView
from django.urls import reverse_lazy
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required

@login_required
def create_product(request):
    form = ProductCreateForm(request.POST or None)
    if form.is_valid():
        product = form.save(commit=False)
        product.user = request.user
        product.save()
        return HttpResponseRedirect(reverse("product:list_product"))
    return render(request, "form.html", {"form": form})

class CreateProduct(CreateView):
    model = Product
    form_class = ProductCreateForm
    template_name = "form.html"
    success_url = reverse_lazy("product:list_product")

    def form_valid(self, form):
        product = form.save(commit=False)
        product.user = self.request.user
        product.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Add Product"
        return context

@login_required
def list_product(request):
    product_list = Product.objects.filter(user=request.user)
    return render(request, "product_list.html", {"products": product_list, "title": "Product List"})


def edit_product(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    form = ProductCreateForm(request.POST or None, instance=product)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse("product:list_product"))
    return render(request, "form.html", {"form": form})

def delete_product(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    product.delete()
    return HttpResponseRedirect(reverse("product:list_product"))

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("user:login"))

useraccount/views.py
from django.shortcuts import render, reverse
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.views import LoginView
from django.views.generic import CreateView
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from useraccount.forms import CustomUserCreationForm
from django.core.mail import send_mail
from django.template.loader import render_to_string


class UserLogin(LoginView):
    template_name = "login.html"
    redirect_authenticated_user = True


class UserSignupView(CreateView):
    model = User
    template_name = "signup.html"
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("user:login")


def send_email_to_user(request):
    subject = "Testing Django Email"
    message = "Hello, we are testing our django email."
    from_email = "ytddash@gmail.com"
    recipient_list = ["officialtam01@gmail.com",]
    html_message = render_to_string("email.html", {"name": "Satyam"})
    val = send_mail(subject, message, from_email, recipient_list, html_message=html_message)
    return HttpResponse(val)

product/templates/form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <form method="POST" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="submit" value="Submit" />
    </form>
</div>
{% endblock content %}

product/templates/product_list.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div>
        <a href="{% url 'product:add_product' %}">Add New Product</a>
        <a href="{% url 'product:logout' %}">Logout</a>
    </div>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Weight</th>
                    <th>Name</th>
                    <th>Price</th>
                    <th>Customer Name</th>
                    <th>Customer Contact 1</th>
                    <th>Customer Contact 2</th>
                    <th>Status</th>
                    <th>Remarks</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for product in products %}
                <tr>
                    <td>{{ product.weight.weight_range }}</td>
                    <td>
                        <a href="{% url 'product:edit_product' product.id %}">{{ product.name }}</a>
                    </td>
                    <td>{{ product.price }}</td>
                    <td>{{ product.customer_fullname }}</td>
                    <td>{{ product.customer_contact1 }}</td>
                    <td>{{ product.customer_contact2 }}</td>
                    <td>{{ product.status }}</td>
                    <td>{{ product.remarks }}</td>
                    <td>
                        <a href="{% url 'product:edit_product' product.id %}" class="btn btn-info">Edit</a>
                        <a href="{% url 'product:delete_product' product.id %}" class="btn btn-danger">Delete</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>{{ title }}</title>
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" />
</head>

<body>
    {% block content %}
    {% endblock content %}
</body>

</html>

useraccount/templates/email.html
<p style="color:chartreuse;">Hello, {{ name }}!</p>
<p style="color: teal;">Welcome to our email list.</p>

useraccount/templates/login.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <form method="POST" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-primary" type="submit" name="login" value="Log In" />
    </form>
</div>
{% endblock content %}

useraccount/templates/signup.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <form method="POST" action="">
        {% csrf_token %}
        {% for field in form %}
        <div class="form-group">
            {{ field.errors }}
            {{ field.label_tag }}
            {{ field }}
            {% if field.help_text %}
            <p class="text text-muted">{{ field.help_text | safe }}</p>
            {% endif %}
        </div>
        {% endfor %}
        <input class="btn btn-info" type="submit" name="signup" value="Register" />
    </form>
</div>
{% endblock content %}